services:
  app:
    container_name: soulmate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
